//Euler Problem 45 (http://projecteuler.net/problem=45)

/* Problem:	
	Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.



*/

/* Lösung (Nr. 48396, 2016/05/08):

	1533776805

*/


// Erklärung siehe unterhalb des Programms

//

package euler.euler33_50;

public class Euler45 {
	
	public static void main(String[] args) {

		long timer = System.currentTimeMillis();

		long solution = 0;
		
		long hex = 1;
		int counterHex = 1;
		long pent = 1;
		int counterPent = 1;
		long tri = 1;
		int counterTri = 1;
		
		while (true)
		{
			counterHex++;
			hex += 4 * counterHex - 3;
			
			while (pent < hex)
			{
				counterPent++;
				pent += 3 * counterPent -2;
			}
			
			while (tri < hex)
			{
				counterTri++;
				tri += counterTri;
			}
			
			if ( (hex == pent) && (hex == tri) )
			{
				System.out.println("Found solution: " + hex + " Indizes: Hex: " + counterHex + " Pent: " + counterPent + " Tri: " + counterTri);
				if (hex > 40755)
				{
					solution = hex;
					break;
				}
			}
			
//			if (hex > 10_000_000_000L)
//			{
//				System.out.println("Breaking " + hex);
//				break;
//			}
			
		}

		System.out.println("Result: " + solution);		
		
		System.out.println("Elapsed time: " + (System.currentTimeMillis() - timer) + "ms");	
	
	}
	
	

}






/* Erklärung:
	1. Grundüberlegungen:
		- Hexagonale Zahlen haben groessere Abstaende
		- Abstaende: 
			- Hexa: n(2n-1) - (n-1)(2(n-1)-1) = 2n^2 - n - 2(n-1)^2 + n - 1 = 2n^2 - n - 2n^2 + 4n - 2 + n - 1 = 4n - 3
			- Penta: 3n-2 (siehe Euler44)
			- Tri: n(n+2)/2 - (n-1)(n-1+1)/2 = ( n^2 + 2n - n^2 + n )/2 = n  
	2. Brute Force Prinzip:
		a) Laufe die hexagonalen Zahlen hoch und teste, ob sie auch pentagonal und triangulaer sind
		b) Genauer: 
			1. Gehe zur naechsten Hexagonalzahl
			2. Teste, ob die gegenwaertige Pentagonalzahl kleiner ist. Wenn ja, laufe die Pentagonalzahlen hoch, bis >= der Hexagonalzahl
			3. Wenn Hexagonalzahl auch pentagonal ist, so tue das selbe nochmal fuer die Triangulaerzahl
	3. Optimierungen:
		- Nicht gemacht: Weil jede Hexagonalzahl bereits triangulaer ist, koennte man sich diesen Test sparen

*/
